Asseco/Controllers/UserInformationController.cs
using Asseco.Data;
using Asseco.Models;
using Microsoft.AspNetCore.Mvc;

namespace Asseco.Controllers
{
    public class UserInformationController : Controller
    {

        private readonly ApplicationDbContext _db;
        public JsonController jsonController = new JsonController();
        public EmailController emailController = new EmailController();


        public UserInformationController(ApplicationDbContext db)
        {
            _db = db;
        }

        

        public IActionResult Index()
        {
            
            IEnumerable<UserInformation> userList = _db.UserInformation;
            return View(userList);
        }

        

        // Create

        [HttpGet("Limit")]
        public IActionResult Create()
        {
            return View("Create");
        }  

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreatePost(UserInformation? obj)
        {

            jsonController.Json(obj);
            _db.UserInformation.Add(obj);
            _db.SaveChanges();
            emailController.Email(obj);
            return RedirectToAction("Index");

        }



        // Details

        public IActionResult Details(int? Id)
        {
            if(Id == null || Id == 0)
            {
                return NotFound();
            }

            var obj = _db.UserInformation.Find(Id);

            if(obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }


        // Edit

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditPost(UserInformation obj)
        {
            jsonController.Json(obj);
            _db.UserInformation.Update(obj);
            _db.SaveChanges();
            emailController.Email(obj);
            return RedirectToAction("Index");
        }


        // Delete

        public IActionResult Delete(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }

            var obj = _db.UserInformation.Find(Id);

            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(UserInformation obj)
        {
            _db.UserInformation.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }


        // .biz Mail

        public IActionResult SearchForBizMail()
        {
            var biz = from g in _db.UserInformation where g.Email.EndsWith(".biz") select g;
            return View(biz);
        }
    }
}

Asseco/Views/Shared/_DisplayUserPartial.cshtml
@model Asseco.Models.UserInformation


 <div class="container border mb-3 p-3">
     <div class="container">
         <div class="row">
             <h1 class="text-primary">New user</h1>
         </div>
     </div>

     <div class="row mb-3">
         <div class="col-3">
             <label asp-for="Name"></label>
         </div>
         <div class="col-9">
             <input asp-for="Name" class="form-control"/>
             <span asp-validation-for="Name" class="text-danger"></span>
         </div>
     </div>

      <div class="row mb-3">
         <div class="col-3">
             <label asp-for="Lastname"></label>
         </div>
         <div class="col-9">
             <input asp-for="Lastname" class="form-control"/>
             <span asp-validation-for="Lastname" class="text-danger"></span>
         </div>
     </div>

      <div class="row">
         <div class="col-3">
             <label asp-for="Email"></label>
         </div>
         <div class="col-9">
             <input asp-for="Email" class="form-control"/>
             <span asp-validation-for="Email" class="text-danger"></span>
         </div>
     </div>
</div>


<div class="container border mb-3 p-3">

    <div class="row">
        <h1 class="text-primary">Adrdress</h1>
    </div>

    <div class="row mb-3">
        <div class="col-3">
            <label asp-for="City"></label>
        </div>
        <div class="col-9">
            <input asp-for="City" class="form-control"/>
        </div>
    </div>

     <div class="row mb-3">
        <div class="col-3">
            <label asp-for="Street"></label>
        </div>
        <div class="col-9">
            <input asp-for="Street" class="form-control"/>
        </div>
    </div>

     <div class="row mb-3">
        <div class="col-3">
            <label asp-for="Suite"></label>
        </div>
        <div class="col-9">
            <input asp-for="Suite" class="form-control"/>
        </div>
    </div>

     <div class="row mb-3">
        <div class="col-3">
            <label asp-for="Zipcode"></label>
        </div>
        <div class="col-9">
            <input asp-for="Zipcode" class="form-control"/>
        </div>
    </div>

     <div class="row mb-3">
        <div class="col-3">
            <label asp-for="Lat"></label>
        </div>
        <div class="col-9">
            <input asp-for="Lat" class="form-control"/>
        </div>
    </div>

     <div class="row">
        <div class="col-3">
            <label asp-for="Lng"></label>
        </div>
        <div class="col-9">
            <input asp-for="Lng" class="form-control"/>
        </div>
    </div>
</div>

<div class="container border p-3">

    <div class="row">
        <h1 class="text-primary">Company</h1>
    </div>

    <div class="row mb-3">
        <div class="col-3">
            <label asp-for="Phone"></label>
        </div>
        <div class="col-9">
            <input asp-for="Phone" class="form-control"/>
        </div>
    </div>

     <div class="row mb-3">
        <div class="col-3">
            <label asp-for="Website"></label>
        </div>
        <div class="col-9">
            <input asp-for="Website" class="form-control"/>
        </div>
    </div>

     <div class="row mb-3">
        <div class="col-3">
            <label asp-for="CompanyName"></label>
        </div>
        <div class="col-9">
            <input asp-for="CompanyName" class="form-control"/>
            
        </div>
    </div>

     <div class="row mb-3">
        <div class="col-3">
            <label asp-for="CompanyCatchPhrase"></label>
        </div>
        <div class="col-9">
            <input asp-for="CompanyCatchPhrase" class="form-control"/>
        </div>
    </div>

      <div class="row">
        <div class="col-3">
            <label asp-for="Bs"></label>
        </div>
        <div class="col-9">
            <input asp-for="Bs" class="form-control"/>
        </div>
    </div>
</div>

Asseco/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Asseco</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Asseco.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Asseco</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserInformation" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserInformation" asp-action="SearchForBizMail">Biz mail</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Asseco - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>